# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_name',
            new_name='name',
        ),
    ]
