# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180117_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
